In [1]:
import pandas as pd
import re
rep="/Volumes/BroadExt/sDrive/Recherche/Boye/HDR/Data/vlexique2.0.3/"

In [2]:
fParadigms="vlexique_paradigms.csv"
fFeatures="vlexique_features.csv"
fLexemes="vlexique_lexemes.csv"
fSounds="vlexique_sounds.csv"
fTags="vlexique_tags.csv"
fCells="vlexique_cells.csv"

dfParadigms=pd.read_csv(rep+fParadigms)
dfFeatures=pd.read_csv(rep+fFeatures)
dfLexemes=pd.read_csv(rep+fLexemes)
dfSounds=pd.read_csv(rep+fSounds)
dfTags=pd.read_csv(rep+fTags)
dfCells=pd.read_csv(rep+fCells)

In [3]:
dGrace=dfCells[["cell_id","GRACE"]].set_index("cell_id").to_dict()["GRACE"]
dSwim={}
for k,v in dGrace.items():
    # pour les formes finies, on a un matching m
    m=re.match("Vm(.)(.)([123][sp])-",v)
    if m:
        # le passé simple est codé s en GRACE mais a pour SWIM
        # l'impératif est codé m en GRACE mais I pour SWIM
        dSwim[k]=m.group(2).replace("s","a")+m.group(1).replace("m","I")+m.group(3).upper()
    else:
        m=re.match("Vmp(.)-(.)(.)",v)
        if m:
            if m.group(1)=="p":
                dSwim[k]="pP"
            else:
                dSwim[k]="pp"+m.group(3).upper()+m.group(2).upper()
        else:
            dSwim[k]="inf"
dSwim

{'cond.prs.1.pl': 'pc1P',
 'cond.prs.1.sg': 'pc1S',
 'cond.prs.2.pl': 'pc2P',
 'cond.prs.2.sg': 'pc2S',
 'cond.prs.3.pl': 'pc3P',
 'cond.prs.3.sg': 'pc3S',
 'imp.prs.1.pl': 'pI1P',
 'imp.prs.2.pl': 'pI2P',
 'imp.prs.2.sg': 'pI2S',
 'ind.fut.1.pl': 'fi1P',
 'ind.fut.1.sg': 'fi1S',
 'ind.fut.2.pl': 'fi2P',
 'ind.fut.2.sg': 'fi2S',
 'ind.fut.3.pl': 'fi3P',
 'ind.fut.3.sg': 'fi3S',
 'ind.ipfv.1.pl': 'ii1P',
 'ind.ipfv.1.sg': 'ii1S',
 'ind.ipfv.2.pl': 'ii2P',
 'ind.ipfv.2.sg': 'ii2S',
 'ind.ipfv.3.pl': 'ii3P',
 'ind.ipfv.3.sg': 'ii3S',
 'ind.prs.1.pl': 'pi1P',
 'ind.prs.1.sg': 'pi1S',
 'ind.prs.2.pl': 'pi2P',
 'ind.prs.2.sg': 'pi2S',
 'ind.prs.3.pl': 'pi3P',
 'ind.prs.3.sg': 'pi3S',
 'ind.pst.1.pl': 'ai1P',
 'ind.pst.1.sg': 'ai1S',
 'ind.pst.2.pl': 'ai2P',
 'ind.pst.2.sg': 'ai2S',
 'ind.pst.3.pl': 'ai3P',
 'ind.pst.3.sg': 'ai3S',
 'inf': 'inf',
 'ptcp.prs': 'pP',
 'ptcp.pst.f.pl': 'ppFP',
 'ptcp.pst.f.sg': 'ppFS',
 'ptcp.pst.m.pl': 'ppMP',
 'ptcp.pst.m.sg': 'ppMS',
 'sbjv.prs.1.pl': 'ps1P',
 'sbjv.prs.1.sg': 'ps1S',
 'sbjv.prs.2.pl': 'ps2P',
 'sbjv.prs.2.sg': 'ps2S',
 'sbjv.prs.3.pl': 'ps3P',
 'sbjv.prs.3.sg': 'ps3S',
 'sbjv.pst.1.pl': 'is1P',
 'sbjv.pst.1.sg': 'is1S',
 'sbjv.pst.2.pl': 'is2P',
 'sbjv.pst.2.sg': 'is2S',
 'sbjv.pst.3.pl': 'is3P',
 'sbjv.pst.3.sg': 'is3S'}

In [5]:
%store dSwim

Stored 'dSwim' (dict)

In [34]:
sounds=dfSounds.sound_id.unique().tolist()
print(", ".join(sounds))

p, b, t, d, k, g, f, v, s, z, ʃ, ʒ, m, n, ɲ, ŋ, ʁ, l, j, w, ɥ, i, y, u, E, e, ɛ, Ø, ə, ø, œ, O, o, ɔ, a, ɛ̃, œ̃, ɑ̃, ɔ̃

In [35]:
dSound={"ʃ":"S","ʒ":"Z","ɲ":"J","ŋ":"N","ʁ":"r","ɥ":"H",
        "ɛ":"E","Ø":"2","ə":"6","ø":"2","œ":"9","ɔ":"O",
        "ɛ̃":"ê","œ̃":"û","ɑ̃":"â","ɔ̃":"ô"}

def mapSounds(chaine):
    result=chaine
    result=result.replace("ɛ̃","ê")
    result=result.replace("œ̃","û")
    result=result.replace("ɑ̃","â")
    result=result.replace("ɔ̃","ô")
    for sound in dSound:
        result=result.replace(sound,dSound[sound])
    return result.replace(" ","")

In [36]:
mapSounds("a b ɛ s ə ʁ j ɔ̃")

'abEs6rjô'

In [37]:
dfParadigms.loc[(dfParadigms.lexeme=="catir")]

,form_id,lexeme,cell,phon_form,orth_form,overabundance_tag,frequency,frequency_per_million
37995,form-catir-cond-1pl,catir,cond.prs.1.pl,k a t i ʁ j ɔ̃,catirions,NaN,0,0.0
37996,form-catir-cond-1sg,catir,cond.prs.1.sg,k a t i ʁ E,catirais,NaN,0,0.0
37997,form-catir-cond-2pl,catir,cond.prs.2.pl,k a t i ʁ j e,catiriez,NaN,0,0.0
37998,form-catir-cond-2sg,catir,cond.prs.2.sg,k a t i ʁ E,catirais,NaN,0,0.0
37999,form-catir-cond-3pl,catir,cond.prs.3.pl,k a t i ʁ E,catiraient,NaN,0,0.0
38000,form-catir-cond-3sg,catir,cond.prs.3.sg,k a t i ʁ E,catirait,NaN,0,0.0
38001,form-catir-fut-1pl,catir,ind.fut.1.pl,k a t i ʁ ɔ̃,catirons,NaN,0,0.0
38002,form-catir-fut-1sg,catir,ind.fut.1.sg,k a t i ʁ E,catirai,NaN,0,0.0
38003,form-catir-fut-2pl,catir,ind.fut.2.pl,k a t i ʁ e,catirez,NaN,0,0.0
38004,form-catir-fut-2sg,catir,ind.fut.2.sg,k a t i ʁ a,catiras,NaN,0,0.0
38005,form-catir-fut-3pl,catir,ind.fut.3.pl,k a t i ʁ ɔ̃,catiront,NaN,0,0.0
38006,form-catir-fut-3sg,catir,ind.fut.3.sg,k a t i ʁ a,catira,NaN,0,0.0
38007,form-catir-imp-1pl,catir,imp.prs.1.pl,k a t i s ɔ̃,catissons,NaN,0,0.0
38008,form-catir-imp-2pl,catir,imp.prs.2.pl,k a t i s e,catissez,NaN,0,0.0
38009,form-catir-imp-2sg,catir,imp.prs.2.sg,k a t i,catis,NaN,0,0.0
38010,form-catir-inf,catir,inf,k a t i ʁ,catir,NaN,0,0.0
38011,form-catir-ipfv-1pl,catir,ind.ipfv.1.pl,k a t i s j ɔ̃,catissions,NaN,0,0.0
38012,form-catir-ipfv-1sg,catir,ind.ipfv.1.sg,k a t i s E,catissais,NaN,0,0.0
38013,form-catir-ipfv-2pl,catir,ind.ipfv.2.pl,k a t i s j e,catissiez,NaN,0,0.0
38014,form-catir-ipfv-2sg,catir,ind.ipfv.2.sg,k a t i s E,catissais,NaN,0,0.0
38015,form-catir-ipfv-3pl,catir,ind.ipfv.3.pl,k a t i s E,catissaient,NaN,0,0.0
38016,form-catir-ipfv-3sg,catir,ind.ipfv.3.sg,k a t i s E,catissait,NaN,0,0.0
38017,form-catir-prs-1pl,catir,ind.prs.1.pl,k a t i s ɔ̃,catissons,NaN,0,0.0
38018,form-catir-prs-1sg,catir,ind.prs.1.sg,k a t i,catis,NaN,0,0.0
38019,form-catir-prs-2pl,catir,ind.prs.2.pl,k a t i s e,catis,NaN,0,0.0
38020,form-catir-prs-2sg,catir,ind.prs.2.sg,k a t i,catis,specific,0,0.0
38021,form-catir-prs-2sg2,catir,ind.prs.2.sg,k a t i s,catisses,specific,0,0.0
38022,form-catir-prs-3pl,catir,ind.prs.3.pl,k a t i s,catissent,NaN,0,0.0
38023,form-catir-prs-3sg,catir,ind.prs.3.sg,k a t i,catit,NaN,0,0.0
38024,form-catir-prs-ptcp,catir,ptcp.prs,k a t i s ɑ̃,catissant,NaN,0,0.0
38025,form-catir-pst-1pl,catir,ind.pst.1.pl,k a t i m,catîmes,NaN,0,0.0
38026,form-catir-pst-1sg,catir,ind.pst.1.sg,k a t i,catis,NaN,0,0.0
38027,form-catir-pst-2pl,catir,ind.pst.2.pl,k a t i t,catîtes,NaN,0,0.0
38028,form-catir-pst-2sg,catir,ind.pst.2.sg,k a t i,catis,NaN,0,0.0
38029,form-catir-pst-3pl,catir,ind.pst.3.pl,k a t i ʁ,catirent,NaN,0,0.0
38030,form-catir-pst-3sg,catir,ind.pst.3.sg,k a t i,catit,NaN,0,0.0
38031,form-catir-pst-ptcp-f-pl,catir,ptcp.pst.f.pl,k a t i,caties,NaN,0,0.0
38032,form-catir-pst-ptcp-f-sg,catir,ptcp.pst.f.sg,k a t i,catie,NaN,0,0.0
38033,form-catir-pst-ptcp-m-pl,catir,ptcp.pst.m.pl,k a t i,catis,NaN,0,0.0
38034,form-catir-pst-ptcp-m-sg,catir,ptcp.pst.m.sg,k a t i,cati,NaN,0,0.0
38035,form-catir-pst-sbjv-1pl,catir,sbjv.pst.1.pl,k a t i s j ɔ̃,catissions,NaN,0,0.0
38036,form-catir-pst-sbjv-1sg,catir,sbjv.pst.1.sg,k a t i s,catisse,NaN,0,0.0
38037,form-catir-pst-sbjv-2pl,catir,sbjv.pst.2.pl,k a t i s j e,catissiez,NaN,0,0.0
38038,form-catir-pst-sbjv-2sg,catir,sbjv.pst.2.sg,k a t i s,catisses,NaN,0,0.0
38039,form-catir-pst-sbjv-3pl,catir,sbjv.pst.3.pl,k a t i s,catissent,NaN,0,0.0
38040,form-catir-pst-sbjv-3sg,catir,sbjv.pst.3.sg,k a t i,catît,NaN,0,0.0
38041,form-catir-sbjv-1pl,catir,sbjv.prs.1.pl,k a t i s j ɔ̃,catissions,NaN,0,0.0
38042,form-catir-sbjv-1sg,catir,sbjv.prs.1.sg,k a t i s,catisse,NaN,0,0.0
38043,form-catir-sbjv-2pl,catir,sbjv.prs.2.pl,k a t i s j e,catissiez,NaN,0,0.0
38044,form-catir-sbjv-2sg,catir,sbjv.prs.2.sg,k a t i s,catisses,NaN,0,0.0
38045,form-catir-sbjv-3pl,catir,sbjv.prs.3.pl,k a t i s,catissent,NaN,0,0.0
38046,form-catir-sbjv-3sg,catir,sbjv.prs.3.sg,k a t i s,catisse,NaN,0,0.0

### Corrections phonétiques et orthographique

In [38]:
specifics=dfParadigms.loc[(dfParadigms.overabundance_tag=="specific")]["lexeme"].unique().tolist()

# corrections 2.0.3 pour asseoir et rasseoir
dfParadigms.loc[(dfParadigms.lexeme=="asseoir")&(dfParadigms.orth_form.str.contains("oi"))&(~dfParadigms.phon_form.str.contains("w a")),"phon_form"]="a s w a"
dfParadigms.loc[(dfParadigms.lexeme=="rasseoir")&(dfParadigms.orth_form.str.contains("oi"))&(~dfParadigms.phon_form.str.contains("w a")),"phon_form"]="r a s w a"

# corrections 2.0.3 pour arguer
dfParadigms.loc[(dfParadigms.lexeme=="arguer")&(dfParadigms.phon_form.str.contains("u")),"phon_form"]=dfParadigms.loc[(dfParadigms.lexeme=="arguer")&(dfParadigms.phon_form.str.contains("u")),"phon_form"].str.replace("u","y")

# corrections 2.0.3 pour catir
dfParadigms.loc[(dfParadigms.lexeme=="catir")&(dfParadigms.cell=="ind.prs.2.pl"),"orth_form"]="catissez"

### Ajout des colonnes sPhon, gCell, sCell,

dfParadigms.loc[:,"sPhon"]=dfParadigms.phon_form.apply(mapSounds)

In [47]:
df=dfParadigms[["orth_form","phon_form","lexeme","frequency","cell","overabundance_tag"]]
df.loc[:,"gCell"]=df["cell"].replace(dGrace)
df.loc[:,"sCell"]=df["cell"].replace(dSwim)
df.loc[:,"sPhon"]=df.phon_form.apply(mapSounds)
df

/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_1057/3994357018.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,"gCell"]=df["cell"].replace(dGrace)

,orth_form,phon_form,lexeme,frequency,cell,overabundance_tag,gCell,sCell,sPhon
0,abaisserions,a b ɛ s ə ʁ j ɔ̃,abaisser,0,cond.prs.1.pl,NaN,Vmcp1p-,pc1P,abEs6rjô
1,abaisserais,a b ɛ s ə ʁ E,abaisser,38,cond.prs.1.sg,NaN,Vmcp1s-,pc1S,abEs6rE
2,abaisseriez,a b ɛ s ə ʁ j e,abaisser,9,cond.prs.2.pl,NaN,Vmcp2p-,pc2P,abEs6rje
3,abaisserais,a b ɛ s ə ʁ E,abaisser,14,cond.prs.2.sg,NaN,Vmcp2s-,pc2S,abEs6rE
4,abaisseraient,a b ɛ s ə ʁ E,abaisser,4,cond.prs.3.pl,NaN,Vmcp3p-,pc3P,abEs6rE
...,...,...,...,...,...,...,...,...,...
274891,sois,s w a,être,15983,sbjv.prs.1.sg,NaN,Vmsp1s-,ps1S,swa
274892,soyez,s w a j e,être,13798,sbjv.prs.2.pl,NaN,Vmsp2p-,ps2P,swaje
274893,sois,s w a,être,26590,sbjv.prs.2.sg,NaN,Vmsp2s-,ps2S,swa
274894,soient,s w a,être,21743,sbjv.prs.3.pl,NaN,Vmsp3p-,ps3P,swa
274895,soit,s w a,être,183040,sbjv.prs.3.sg,NaN,Vmsp3s-,ps3S,swa

### Filtrage des surabondances et des défectivités marquées

In [63]:
dfSelect=df.loc[(df.overabundance_tag.isnull())&(df.phon_form!="#DEF#")][["orth_form","sPhon","lexeme","frequency","sCell"]]
dfSelect.columns=["ortho","phono","lexeme","tir1","case"]
dfSelect.loc[(dfSelect.lexeme=="asseoir"),:]

            ortho   phono   lexeme   tir1  case
16215     asseoir   aswar  asseoir  16152   inf
16242     assîmes    asim  asseoir      3  ai1P
16243       assis     asi  asseoir     31  ai1S
16244     assîtes    asit  asseoir      0  ai2P
16245       assis     asi  asseoir     16  ai2S
16246    assirent    asir  asseoir     18  ai3P
16247       assit     asi  asseoir    143  ai3S
16248     assises    asiz  asseoir    232  ppFP
16249      assise    asiz  asseoir   5174  ppFS
16250       assis     asi  asseoir   1838  ppMP
16251       assis     asi  asseoir  15615  ppMS
16252  assissions  asisjô  asseoir      0  is1P
16253     assisse    asis  asseoir      0  is1S
16254   assissiez  asisje  asseoir      0  is2P
16255    assisses    asis  asseoir      0  is2S
16256   assissent    asis  asseoir      0  is3P
16257       assît     asi  asseoir      0  is3S

In [64]:
dfOut=dfSelect.groupby(["phono","lexeme","case"])[["ortho","tir1"]].agg({"ortho":list,"tir1":"sum"}).reset_index()
dfOut["ortho"]=dfOut["ortho"].str.join(",")
dfOut.loc[dfOut.lexeme=="abréger",:]

           phono   lexeme  case          ortho  tir1
28829      abrEZ  abréger  pI2S         abrège    95
28830      abrEZ  abréger  pi1S         abrège    45
28831      abrEZ  abréger  pi2S        abrèges     6
28832      abrEZ  abréger  pi3P       abrègent     9
28833      abrEZ  abréger  pi3S         abrège    35
28834      abrEZ  abréger  ps1S         abrège    10
28835      abrEZ  abréger  ps2S        abrèges     0
28836      abrEZ  abréger  ps3P       abrègent     1
28837      abrEZ  abréger  ps3S         abrège    17
28838     abrEZE  abréger  ai1S       abrégeai     0
28839     abrEZE  abréger  ii1S      abrégeais     0
28840     abrEZE  abréger  ii2S      abrégeais     2
28841     abrEZE  abréger  ii3P    abrégeaient     0
28842     abrEZE  abréger  ii3S      abrégeait     5
28843    abrEZEr  abréger  ai3P     abrégèrent     0
28844     abrEZa  abréger  ai2S       abrégeas     0
28845     abrEZa  abréger  ai3S        abrégea     1
28846     abrEZa  abréger  is3S       abrégeât     0
28847    abrEZam  abréger  ai1P     abrégeâmes     0
28848    abrEZas  abréger  is1S     abrégeasse     0
28849    abrEZas  abréger  is2S    abrégeasses     0
28850    abrEZas  abréger  is3P   abrégeassent     0
28851  abrEZasje  abréger  is2P   abrégeassiez     0
28852  abrEZasjô  abréger  is1P  abrégeassions     0
28853    abrEZat  abréger  ai2P     abrégeâtes     0
28854     abrEZe  abréger   inf        abréger   423
28855     abrEZe  abréger  pI2P        abrégez    44
28856     abrEZe  abréger  pi2P        abrégez     5
28857     abrEZe  abréger  ppFP       abrégées     7
28858     abrEZe  abréger  ppFS        abrégée    27
28859     abrEZe  abréger  ppMP        abrégés    18
28860     abrEZe  abréger  ppMS         abrégé   128
28861    abrEZje  abréger  ii2P       abrégiez     1
28862    abrEZje  abréger  ps2P       abrégiez     0
28863    abrEZjô  abréger  ii1P      abrégions     0
28864    abrEZjô  abréger  ps1P      abrégions     1
28865     abrEZâ  abréger    pP      abrégeant     4

In [68]:
# dfOut.to_csv(rep+"vlexique2-tir.csv",sep="\t",encoding="utf8")
dfOut.to_pickle(rep+"vlexique2-filtre.pkl")

In [70]:
dfOut.pivot(index="lexeme",columns="case",values="phono").to_csv(rep+"vlexique2-filtre.csv",sep=";")

In [66]:
pd.read_pickle(rep+"WordStructure/vlexique2-Total.pkl")

          lexeme  case        ortho   phono    tir1
0       abaisser  ai1P   abaissâmes  abEsam       0
1       abaisser  ai1S     abaissai   abEsE       1
2       abaisser  ai2P   abaissâtes  abEsat       1
3       abaisser  ai2S     abaissas   abEsa       0
4       abaisser  ai3P  abaissèrent  abEsEr       1
...          ...   ...          ...     ...     ...
267760      être  ps1S         sois     swa   15983
267761      être  ps2P        soyez   swaje   13798
267762      être  ps2S         sois     swa   26590
267763      être  ps3P       soient     swa   21743
267764      être  ps3S         soit     swa  183040

[267765 rows x 5 columns]