In [1]:
import pandas as pd
import re
rep="/Volumes/BroadExt/sDrive/Recherche/Boye/HDR/Data/vlexique2.0.3/"

In [2]:
fParadigms="vlexique_paradigms.csv"
fFeatures="vlexique_features.csv"
fLexemes="vlexique_lexemes.csv"
fSounds="vlexique_sounds.csv"
fTags="vlexique_tags.csv"
fCells="vlexique_cells.csv"

dfParadigms=pd.read_csv(rep+fParadigms)
dfFeatures=pd.read_csv(rep+fFeatures)
dfLexemes=pd.read_csv(rep+fLexemes)
dfSounds=pd.read_csv(rep+fSounds)
dfTags=pd.read_csv(rep+fTags)
dfCells=pd.read_csv(rep+fCells)

In [3]:
dGrace=dfCells[["cell_id","GRACE"]].set_index("cell_id").to_dict()["GRACE"]
dSwim={}
for k,v in dGrace.items():
    # pour les formes finies, on a un matching m
    m=re.match("Vm(.)(.)([123][sp])-",v)
    if m:
        # le passé simple est codé s en GRACE mais a pour SWIM
        # l'impératif est codé m en GRACE mais I pour SWIM
        dSwim[k]=m.group(2).replace("s","a")+m.group(1).replace("m","I")+m.group(3).upper()
    else:
        m=re.match("Vmp(.)-(.)(.)",v)
        if m:
            if m.group(1)=="p":
                dSwim[k]="pP"
            else:
                dSwim[k]="pp"+m.group(3).upper()+m.group(2).upper()
        else:
            dSwim[k]="inf"
dSwim

{'cond.prs.1.pl': 'pc1P',
 'cond.prs.1.sg': 'pc1S',
 'cond.prs.2.pl': 'pc2P',
 'cond.prs.2.sg': 'pc2S',
 'cond.prs.3.pl': 'pc3P',
 'cond.prs.3.sg': 'pc3S',
 'imp.prs.1.pl': 'pI1P',
 'imp.prs.2.pl': 'pI2P',
 'imp.prs.2.sg': 'pI2S',
 'ind.fut.1.pl': 'fi1P',
 'ind.fut.1.sg': 'fi1S',
 'ind.fut.2.pl': 'fi2P',
 'ind.fut.2.sg': 'fi2S',
 'ind.fut.3.pl': 'fi3P',
 'ind.fut.3.sg': 'fi3S',
 'ind.ipfv.1.pl': 'ii1P',
 'ind.ipfv.1.sg': 'ii1S',
 'ind.ipfv.2.pl': 'ii2P',
 'ind.ipfv.2.sg': 'ii2S',
 'ind.ipfv.3.pl': 'ii3P',
 'ind.ipfv.3.sg': 'ii3S',
 'ind.prs.1.pl': 'pi1P',
 'ind.prs.1.sg': 'pi1S',
 'ind.prs.2.pl': 'pi2P',
 'ind.prs.2.sg': 'pi2S',
 'ind.prs.3.pl': 'pi3P',
 'ind.prs.3.sg': 'pi3S',
 'ind.pst.1.pl': 'ai1P',
 'ind.pst.1.sg': 'ai1S',
 'ind.pst.2.pl': 'ai2P',
 'ind.pst.2.sg': 'ai2S',
 'ind.pst.3.pl': 'ai3P',
 'ind.pst.3.sg': 'ai3S',
 'inf': 'inf',
 'ptcp.prs': 'pP',
 'ptcp.pst.f.pl': 'ppFP',
 'ptcp.pst.f.sg': 'ppFS',
 'ptcp.pst.m.pl': 'ppMP',
 'ptcp.pst.m.sg': 'ppMS',
 'sbjv.prs.1.pl': 'ps1P',
 'sbjv.prs.1.sg': 'ps1S',
 'sbjv.prs.2.pl': 'ps2P',
 'sbjv.prs.2.sg': 'ps2S',
 'sbjv.prs.3.pl': 'ps3P',
 'sbjv.prs.3.sg': 'ps3S',
 'sbjv.pst.1.pl': 'is1P',
 'sbjv.pst.1.sg': 'is1S',
 'sbjv.pst.2.pl': 'is2P',
 'sbjv.pst.2.sg': 'is2S',
 'sbjv.pst.3.pl': 'is3P',
 'sbjv.pst.3.sg': 'is3S'}

In [4]:
sounds=dfSounds.sound_id.unique().tolist()
print(", ".join(sounds))

p, b, t, d, k, g, f, v, s, z, ʃ, ʒ, m, n, ɲ, ŋ, ʁ, l, j, w, ɥ, i, y, u, E, e, ɛ, Ø, ə, ø, œ, O, o, ɔ, a, ɛ̃, œ̃, ɑ̃, ɔ̃

In [5]:
dSound={"ʃ":"S","ʒ":"Z","ɲ":"J","ŋ":"N","ʁ":"r","ɥ":"H",
        "ɛ":"E","Ø":"2","ə":"6","ø":"2","œ":"9","ɔ":"O",
        "ɛ̃":"ê","œ̃":"û","ɑ̃":"â","ɔ̃":"ô"}

def mapSounds(chaine):
    result=chaine
    result=result.replace("ɛ̃","ê")
    result=result.replace("œ̃","û")
    result=result.replace("ɑ̃","â")
    result=result.replace("ɔ̃","ô")
    for sound in dSound:
        result=result.replace(sound,dSound[sound])
    return result.replace(" ","")

In [6]:
mapSounds("a b ɛ s ə ʁ j ɔ̃")

'abEs6rjô'

In [7]:
specifics=dfParadigms.loc[(dfParadigms.overabundance_tag=="specific")]["lexeme"].unique().tolist()

# corrections 2.0.3 pour asseoir et rasseoir
dfParadigms.loc[(dfParadigms.lexeme=="asseoir")&(dfParadigms.orth_form.str.contains("oi"))&(~dfParadigms.phon_form.str.contains("w a")),"phon_form"]="a s w a"
dfParadigms.loc[(dfParadigms.lexeme=="rasseoir")&(dfParadigms.orth_form.str.contains("oi"))&(~dfParadigms.phon_form.str.contains("w a")),"phon_form"]="r a s w a"

# corrections 2.0.3 pour arguer
dfParadigms.loc[(dfParadigms.lexeme=="arguer")&(dfParadigms.phon_form.str.contains("u")),"phon_form"]=dfParadigms.loc[(dfParadigms.lexeme=="arguer")&(dfParadigms.phon_form.str.contains("u")),"phon_form"].str.replace("u","y")

# corrections 2.0.3 pour catir
dfParadigms.loc[(dfParadigms.lexeme=="catir")&(dfParadigms.cell=="ind.prs.2.pl"),"orth_form"]="catissez"

In [8]:
dfParadigms.loc[:,"sPhon"]=dfParadigms.phon_form.apply(mapSounds)

In [9]:
print(dfParadigms.loc[dfParadigms.lexeme.isin(specifics)].groupby(["lexeme","cell"])[["orth_form","sPhon"]].agg(set).to_string())

                                                        orth_form                         sPhon
lexeme     cell
arguer     cond.prs.1.pl     {arguërions, arguerions, argüerions}           {arg6rjô, argy6rjô}
           cond.prs.1.sg        {arguerais, arguërais, argüerais}             {argy6rE, arg6rE}
           cond.prs.2.pl        {arguëriez, argueriez, argüeriez}           {arg6rje, argy6rje}
           cond.prs.2.sg        {arguerais, arguërais, argüerais}             {argy6rE, arg6rE}
           cond.prs.3.pl  {argueraient, arguëraient, argüeraient}             {argy6rE, arg6rE}
           cond.prs.3.sg        {argüerait, arguërait, arguerait}             {argy6rE, arg6rE}
           imp.prs.1.pl                        {argüons, arguons}                 {argyô, argô}
           imp.prs.2.pl                          {argüez, arguez}                 {argye, arge}
           imp.prs.2.sg                            {argue, argüe}                   {arg, argy}
           ind.fut.1.pl         {arguërons, arguerons, argüerons}             {arg6rô, argy6rô}
           ind.fut.1.sg            {arguerai, arguërai, argüerai}             {argy6rE, arg6rE}
           ind.fut.2.pl            {argüerez, arguërez, arguerez}             {arg6re, argy6re}
           ind.fut.2.sg            {arguëras, argüeras, argueras}             {argy6ra, arg6ra}
           ind.fut.3.pl         {argüeront, argueront, arguëront}             {arg6rô, argy6rô}
           ind.fut.3.sg               {argüera, arguëra, arguera}             {argy6ra, arg6ra}
           ind.ipfv.1.pl                     {argüions, arguions}               {argjô, argyjô}
           ind.ipfv.1.sg                       {argüais, arguais}                 {argyE, argE}
           ind.ipfv.2.pl                       {arguiez, argüiez}               {argyje, argje}
           ind.ipfv.2.sg                       {argüais, arguais}                 {argyE, argE}
           ind.ipfv.3.pl                   {argüaient, arguaient}                 {argyE, argE}
           ind.ipfv.3.sg                       {arguait, argüait}                 {argyE, argE}
           ind.prs.1.pl                        {argüons, arguons}                 {argyô, argô}
           ind.prs.1.sg                            {argue, argüe}                   {arg, argy}
           ind.prs.2.pl                          {argüez, arguez}                 {argye, arge}
           ind.prs.2.sg                  {argues, arguës, argües}                   {arg, argy}
           ind.prs.3.pl                        {arguent, argüent}                   {arg, argy}
           ind.prs.3.sg                            {argue, argüe}                   {arg, argy}
           ind.pst.1.pl                      {arguâmes, argüâmes}               {argam, argyam}
           ind.pst.1.sg                          {argüai, arguai}                 {argyE, argE}
           ind.pst.2.pl                      {arguâtes, argüâtes}               {argyat, argat}
           ind.pst.2.sg                          {arguas, argüas}                 {arga, argya}
           ind.pst.3.pl                    {argüèrent, arguèrent}               {argEr, argyEr}
           ind.pst.3.sg                            {argua, argüa}                 {arga, argya}
           inf                                           {arguer}                        {arge}
           ptcp.prs                            {arguant, argüant}                 {argyâ, argâ}
           ptcp.pst.f.pl                                {arguées}                        {arge}
           ptcp.pst.f.sg                                 {arguée}                        {arge}
           ptcp.pst.m.pl                                 {argués}                        {arge}
           ptcp.pst.m.sg                           {argué, argüé}                 {argye, arge}
           sbjv.prs.1.pl                     {argüions, arguions}               {argjô, argyjô}
           sbjv.prs.1.sg                           {argue, argüe}                   {arg, argy}
           sbjv.prs.2.pl                       {arguiez, argüiez}               {argyje, argje}
           sbjv.prs.2.sg                         {argues, argües}                   {arg, argy}
           sbjv.prs.3.pl                       {arguent, argüent}                   {arg, argy}
           sbjv.prs.3.sg                           {argue, argüe}                   {arg, argy}
           sbjv.pst.1.pl               {argüassions, arguassions}           {argasjô, argyasjô}
           sbjv.pst.1.sg                     {argüasse, arguasse}               {argas, argyas}
           sbjv.pst.2.pl                 {argüassiez, arguassiez}           {argasje, argyasje}
           sbjv.pst.2.sg                   {arguasses, argüasses}               {argas, argyas}
           sbjv.pst.3.pl                 {argüassent, arguassent}               {argas, argyas}
           sbjv.pst.3.sg                         {arguât, argüât}                 {arga, argya}
asseoir    cond.prs.1.pl                 {assiérions, assoirions}            {aswarjô, asjErjô}
           cond.prs.1.sg                   {assiérais, assoirais}              {asjErE, aswarE}
           cond.prs.2.pl                   {assoiriez, assiériez}            {asjErje, aswarje}
           cond.prs.2.sg                   {assiérais, assoirais}              {asjErE, aswarE}
           cond.prs.3.pl               {assiéraient, assoiraient}              {asjErE, aswarE}
           cond.prs.3.sg                   {assiérait, assoirait}              {asjErE, aswarE}
           imp.prs.1.pl                      {assoyons, asseyons}               {asEjô, aswajô}
           imp.prs.2.pl                        {assoyez, asseyez}               {aswaje, asEje}
           imp.prs.2.sg                         {assieds, assois}                  {asje, aswa}
           ind.fut.1.pl                    {assiérons, assoirons}              {aswarô, asjErô}
           ind.fut.1.sg                      {assiérai, assoirai}              {asjErE, aswarE}
           ind.fut.2.pl                      {assiérez, assoirez}              {asjEre, asware}
           ind.fut.2.sg                      {assoiras, assiéras}              {asjEra, aswara}
           ind.fut.3.pl                    {assiéront, assoiront}              {aswarô, asjErô}
           ind.fut.3.sg                        {assoira, assiéra}              {asjEra, aswara}
           ind.ipfv.1.pl                   {asseyions, assoyions}               {asEjô, aswajô}
           ind.ipfv.1.sg                     {asseyais, assoyais}               {asEjE, aswajE}
           ind.ipfv.2.pl                     {asseyiez, assoyiez}               {aswaje, asEje}
           ind.ipfv.2.sg                     {asseyais, assoyais}               {asEjE, aswajE}
           ind.ipfv.3.pl                 {assoyaient, asseyaient}               {asEjE, aswajE}
           ind.ipfv.3.sg                     {assoyait, asseyait}               {asEjE, aswajE}
           ind.prs.1.pl                      {assoyons, asseyons}               {asEjô, aswajô}
           ind.prs.1.sg                         {assieds, assois}                  {asje, aswa}
           ind.prs.2.pl                        {assoyez, asseyez}               {aswaje, asEje}
           ind.prs.2.sg                         {assieds, assois}                  {asje, aswa}
           ind.prs.3.pl                      {asseyent, assoient}                  {asEj, aswa}
           ind.prs.3.sg                          {assoit, assied}                  {asje, aswa}
           ind.pst.1.pl                                 {assîmes}                        {asim}
           ind.pst.1.sg                                   {assis}                         {asi}
           ind.pst.2.pl                                 {assîtes}                        {asit}
           ind.pst.2.sg                                   {assis}                         {asi}
           ind.pst.3.pl                                {assirent}                        {asir}
           ind.pst.3.sg                                   {assit}                         {asi}
           inf                                          {asseoir}                       {aswar}
           ptcp.prs                          {asseyant, assoyant}               {aswajâ, asEjâ}
           ptcp.pst.f.pl                                {assises}                        {asiz}
           ptcp.pst.f.sg                                 {assise}                        {asiz}
           ptcp.pst.m.pl                                  {assis}                         {asi}
           ptcp.pst.m.sg                                  {assis}                         {asi}
           sbjv.prs.1.pl                   {asseyions, assoyions}               {asEjô, aswajô}
           sbjv.prs.1.sg                         {assoie, asseye}                  {asEj, aswa}
           sbjv.prs.2.pl                     {asseyiez, assoyiez}               {aswaje, asEje}
           sbjv.prs.2.sg                       {asseyes, assoies}                  {asEj, aswa}
           sbjv.prs.3.pl                     {asseyent, assoient}                  {asEj, aswa}
           sbjv.prs.3.sg                         {assoie, asseye}                  {asEj, aswa}
           sbjv.pst.1.pl                             {assissions}                      {asisjô}
           sbjv.pst.1.sg                                {assisse}                        {asis}
           sbjv.pst.2.pl                              {assissiez}                      {asisje}
           sbjv.pst.2.sg                               {assisses}                        {asis}
           sbjv.pst.3.pl                              {assissent}                        {asis}
           sbjv.pst.3.sg                                  {assît}                         {asi}
bénir      cond.prs.1.pl                              {bénirions}                     {bEnirjô}
           cond.prs.1.sg                               {bénirais}                      {bEnirE}
           cond.prs.2.pl                               {béniriez}                     {bEnirje}
           cond.prs.2.sg                               {bénirais}                      {bEnirE}
           cond.prs.3.pl                             {béniraient}                      {bEnirE}
           cond.prs.3.sg                               {bénirait}                      {bEnirE}
           imp.prs.1.pl                               {bénissons}                      {bEnisô}
           imp.prs.2.pl                                {bénissez}                      {bEnise}
           imp.prs.2.sg                                   {bénis}                        {bEni}
           ind.fut.1.pl                                {bénirons}                      {bEnirô}
           ind.fut.1.sg                                 {bénirai}                      {bEnirE}
           ind.fut.2.pl                                 {bénirez}                      {bEnire}
           ind.fut.2.sg                                 {béniras}                      {bEnira}
           ind.fut.3.pl                                {béniront}                      {bEnirô}
           ind.fut.3.sg                                  {bénira}                      {bEnira}
           ind.ipfv.1.pl                             {bénissions}                     {bEnisjô}
           ind.ipfv.1.sg                              {bénissais}                      {bEnisE}
           ind.ipfv.2.pl                              {bénissiez}                     {bEnisje}
           ind.ipfv.2.sg                              {bénissais}                      {bEnisE}
           ind.ipfv.3.pl                            {bénissaient}                      {bEnisE}
           ind.ipfv.3.sg                              {bénissait}                      {bEnisE}
           ind.prs.1.pl                               {bénissons}                      {bEnisô}
           ind.prs.1.sg                                   {bénis}                        {bEni}
           ind.prs.2.pl                                {bénissez}                      {bEnise}
           ind.prs.2.sg                                   {bénis}                        {bEni}
           ind.prs.3.pl                               {bénissent}                       {bEnis}
           ind.prs.3.sg                                   {bénit}                        {bEni}
           ind.pst.1.pl                                 {bénîmes}                       {bEnim}
           ind.pst.1.sg                                   {bénis}                        {bEni}
           ind.pst.2.pl                                 {bénîtes}                       {bEnit}
           ind.pst.2.sg                                   {bénis}                        {bEni}
           ind.pst.3.pl                                {bénirent}                       {bEnir}
           ind.pst.3.sg                                   {bénit}                        {bEni}
           inf                                            {bénir}                       {bEnir}
           ptcp.prs                                   {bénissant}                      {bEnisâ}
           ptcp.pst.f.pl                        {bénites, bénies}                 {bEni, bEnit}
           ptcp.pst.f.sg                          {bénie, bénite}                 {bEni, bEnit}
           ptcp.pst.m.pl                          {bénits, bénis}                        {bEni}
           ptcp.pst.m.sg                            {bénit, béni}                        {bEni}
           sbjv.prs.1.pl                             {bénissions}                     {bEnisjô}
           sbjv.prs.1.sg                                {bénisse}                       {bEnis}
           sbjv.prs.2.pl                              {bénissiez}                     {bEnisje}
           sbjv.prs.2.sg                               {bénisses}                       {bEnis}
           sbjv.prs.3.pl                              {bénissent}                       {bEnis}
           sbjv.prs.3.sg                                {bénisse}                       {bEnis}
           sbjv.pst.1.pl                             {bénissions}                     {bEnisjô}
           sbjv.pst.1.sg                                {bénisse}                       {bEnis}
           sbjv.pst.2.pl                              {bénissiez}                     {bEnisje}
           sbjv.pst.2.sg                               {bénisses}                       {bEnis}
           sbjv.pst.3.pl                              {bénissent}                       {bEnis}
           sbjv.pst.3.sg                                  {bénît}                        {bEni}
catir      cond.prs.1.pl                              {catirions}                     {katirjô}
           cond.prs.1.sg                               {catirais}                      {katirE}
           cond.prs.2.pl                               {catiriez}                     {katirje}
           cond.prs.2.sg                               {catirais}                      {katirE}
           cond.prs.3.pl                             {catiraient}                      {katirE}
           cond.prs.3.sg                               {catirait}                      {katirE}
           imp.prs.1.pl                               {catissons}                      {katisô}
           imp.prs.2.pl                                {catissez}                      {katise}
           imp.prs.2.sg                                   {catis}                        {kati}
           ind.fut.1.pl                                {catirons}                      {katirô}
           ind.fut.1.sg                                 {catirai}                      {katirE}
           ind.fut.2.pl                                 {catirez}                      {katire}
           ind.fut.2.sg                                 {catiras}                      {katira}
           ind.fut.3.pl                                {catiront}                      {katirô}
           ind.fut.3.sg                                  {catira}                      {katira}
           ind.ipfv.1.pl                             {catissions}                     {katisjô}
           ind.ipfv.1.sg                              {catissais}                      {katisE}
           ind.ipfv.2.pl                              {catissiez}                     {katisje}
           ind.ipfv.2.sg                              {catissais}                      {katisE}
           ind.ipfv.3.pl                            {catissaient}                      {katisE}
           ind.ipfv.3.sg                              {catissait}                      {katisE}
           ind.prs.1.pl                               {catissons}                      {katisô}
           ind.prs.1.sg                                   {catis}                        {kati}
           ind.prs.2.pl                                {catissez}                      {katise}
           ind.prs.2.sg                         {catis, catisses}                 {katis, kati}
           ind.prs.3.pl                               {catissent}                       {katis}
           ind.prs.3.sg                                   {catit}                        {kati}
           ind.pst.1.pl                                 {catîmes}                       {katim}
           ind.pst.1.sg                                   {catis}                        {kati}
           ind.pst.2.pl                                 {catîtes}                       {katit}
           ind.pst.2.sg                                   {catis}                        {kati}
           ind.pst.3.pl                                {catirent}                       {katir}
           ind.pst.3.sg                                   {catit}                        {kati}
           inf                                            {catir}                       {katir}
           ptcp.prs                                   {catissant}                      {katisâ}
           ptcp.pst.f.pl                                 {caties}                        {kati}
           ptcp.pst.f.sg                                  {catie}                        {kati}
           ptcp.pst.m.pl                                  {catis}                        {kati}
           ptcp.pst.m.sg                                   {cati}                        {kati}
           sbjv.prs.1.pl                             {catissions}                     {katisjô}
           sbjv.prs.1.sg                                {catisse}                       {katis}
           sbjv.prs.2.pl                              {catissiez}                     {katisje}
           sbjv.prs.2.sg                               {catisses}                       {katis}
           sbjv.prs.3.pl                              {catissent}                       {katis}
           sbjv.prs.3.sg                                {catisse}                       {katis}
           sbjv.pst.1.pl                             {catissions}                     {katisjô}
           sbjv.pst.1.sg                                {catisse}                       {katis}
           sbjv.pst.2.pl                              {catissiez}                     {katisje}
           sbjv.pst.2.sg                               {catisses}                       {katis}
           sbjv.pst.3.pl                              {catissent}                       {katis}
           sbjv.pst.3.sg                                  {catît}                        {kati}
communier  cond.prs.1.pl                          {communierions}                   {kOmynirjô}
           cond.prs.1.sg                           {communierais}                    {kOmynirE}
           cond.prs.2.pl                           {communieriez}                   {kOmynirje}

In [10]:
df=dfParadigms[["orth_form","phon_form","lexeme","frequency","cell"]]
df.loc[:,"gCell"]=df["cell"].replace(dGrace)
df.loc[:,"sCell"]=df["cell"].replace(dSwim)
df.loc[:,"sPhon"]=df.phon_form.apply(mapSounds)
df

/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_34672/298172186.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,"gCell"]=df["cell"].replace(dGrace)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_34672/298172186.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,"sCell"]=df["cell"].replace(dSwim)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_34672/298172186.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,"sPhon"]=df.phon_form.apply(mapSounds)

,orth_form,phon_form,lexeme,frequency,cell,gCell,sCell,sPhon
0,abaisserions,a b ɛ s ə ʁ j ɔ̃,abaisser,0,cond.prs.1.pl,Vmcp1p-,pc1P,abEs6rjô
1,abaisserais,a b ɛ s ə ʁ E,abaisser,38,cond.prs.1.sg,Vmcp1s-,pc1S,abEs6rE
2,abaisseriez,a b ɛ s ə ʁ j e,abaisser,9,cond.prs.2.pl,Vmcp2p-,pc2P,abEs6rje
3,abaisserais,a b ɛ s ə ʁ E,abaisser,14,cond.prs.2.sg,Vmcp2s-,pc2S,abEs6rE
4,abaisseraient,a b ɛ s ə ʁ E,abaisser,4,cond.prs.3.pl,Vmcp3p-,pc3P,abEs6rE
...,...,...,...,...,...,...,...,...
274891,sois,s w a,être,15983,sbjv.prs.1.sg,Vmsp1s-,ps1S,swa
274892,soyez,s w a j e,être,13798,sbjv.prs.2.pl,Vmsp2p-,ps2P,swaje
274893,sois,s w a,être,26590,sbjv.prs.2.sg,Vmsp2s-,ps2S,swa
274894,soient,s w a,être,21743,sbjv.prs.3.pl,Vmsp3p-,ps3P,swa
274895,soit,s w a,être,183040,sbjv.prs.3.sg,Vmsp3s-,ps3S,swa

In [11]:
dfSelect=df[["orth_form","sPhon","lexeme","frequency","sCell"]]
dfSelect.columns=["ortho","phono","lexeme","tir1","case"]
dfSelect.loc[(dfSelect.lexeme=="asseoir") & (dfSelect.case.str.startswith("ps")),:]

           ortho   phono   lexeme  tir1  case
16258  asseyions   asEjô  asseoir     6  ps1P
16259  assoyions  aswajô  asseoir     1  ps1P
16260     asseye    asEj  asseoir    59  ps1S
16261     assoie    aswa  asseoir   130  ps1S
16262   asseyiez   asEje  asseoir    37  ps2P
16263   assoyiez  aswaje  asseoir     3  ps2P
16264    asseyes    asEj  asseoir    33  ps2S
16265    assoies    aswa  asseoir    70  ps2S
16266   asseyent    asEj  asseoir    11  ps3P
16267   assoient    aswa  asseoir    36  ps3P
16268     asseye    asEj  asseoir    69  ps3S
16269     assoie    aswa  asseoir   103  ps3S

In [12]:
dfOut=dfSelect.groupby(["phono","lexeme","case"])[["ortho","tir1"]].agg({"ortho":list,"tir1":"sum"}).reset_index()
dfOut["ortho"]=dfOut["ortho"].str.join(",")
dfOut.loc[dfOut.lexeme=="abréger",:]

           phono   lexeme  case                      ortho  tir1
30752      abrEZ  abréger  pI2S                     abrège    95
30753      abrEZ  abréger  pi1S                     abrège    45
30754      abrEZ  abréger  pi2S                    abrèges     6
30755      abrEZ  abréger  pi3P                   abrègent     9
30756      abrEZ  abréger  pi3S                     abrège    35
30757      abrEZ  abréger  ps1S                     abrège    10
30758      abrEZ  abréger  ps2S                    abrèges     0
30759      abrEZ  abréger  ps3P                   abrègent     1
30760      abrEZ  abréger  ps3S                     abrège    17
30761   abrEZ6rE  abréger  fi1S        abrègerai,abrégerai    13
30762   abrEZ6rE  abréger  pc1S      abrègerais,abrégerais     2
30763   abrEZ6rE  abréger  pc2S      abrègerais,abrégerais     0
30764   abrEZ6rE  abréger  pc3P  abrègeraient,abrégeraient     1
30765   abrEZ6rE  abréger  pc3S      abrègerait,abrégerait     6
30766   abrEZ6ra  abréger  fi2S        abrègeras,abrégeras     1
30767   abrEZ6ra  abréger  fi3S          abrègera,abrégera     8
30768   abrEZ6re  abréger  fi2P        abrègerez,abrégerez     2
30769  abrEZ6rje  abréger  pc2P      abrègeriez,abrégeriez     0
30770  abrEZ6rjô  abréger  pc1P    abrègerions,abrégerions     0
30771   abrEZ6rô  abréger  fi1P      abrègerons,abrégerons     0
30772   abrEZ6rô  abréger  fi3P      abrègeront,abrégeront     1
30773     abrEZE  abréger  ai1S                   abrégeai     0
30774     abrEZE  abréger  ii1S                  abrégeais     0
30775     abrEZE  abréger  ii2S                  abrégeais     2
30776     abrEZE  abréger  ii3P                abrégeaient     0
30777     abrEZE  abréger  ii3S                  abrégeait     5
30778    abrEZEr  abréger  ai3P                 abrégèrent     0
30779     abrEZa  abréger  ai2S                   abrégeas     0
30780     abrEZa  abréger  ai3S                    abrégea     1
30781     abrEZa  abréger  is3S                   abrégeât     0
30782    abrEZam  abréger  ai1P                 abrégeâmes     0
30783    abrEZas  abréger  is1S                 abrégeasse     0
30784    abrEZas  abréger  is2S                abrégeasses     0
30785    abrEZas  abréger  is3P               abrégeassent     0
30786  abrEZasje  abréger  is2P               abrégeassiez     0
30787  abrEZasjô  abréger  is1P              abrégeassions     0
30788    abrEZat  abréger  ai2P                 abrégeâtes     0
30789     abrEZe  abréger   inf                    abréger   423
30790     abrEZe  abréger  pI2P                    abrégez    44
30791     abrEZe  abréger  pi2P                    abrégez     5
30792     abrEZe  abréger  ppFP                   abrégées     7
30793     abrEZe  abréger  ppFS                    abrégée    27
30794     abrEZe  abréger  ppMP                    abrégés    18
30795     abrEZe  abréger  ppMS                     abrégé   128
30796    abrEZje  abréger  ii2P                   abrégiez     1
30797    abrEZje  abréger  ps2P                   abrégiez     0
30798    abrEZjô  abréger  ii1P                  abrégions     0
30799    abrEZjô  abréger  ps1P                  abrégions     1
30800     abrEZâ  abréger    pP                  abrégeant     4
30801     abrEZô  abréger  pI1P         abrégeons,abrégons    31
30802     abrEZô  abréger  pi1P         abrégeons,abrégons     1

In [13]:
# dfOut.to_csv(rep+"vlexique2-tir.csv",sep="\t",encoding="utf8")
dfOut.to_pickle(rep+"vlexique2.pkl")

In [15]:
print(dfOut.loc[dfOut.case=="ai3P",:].to_string())

                    phono               lexeme  case                            ortho  tir1
4                   #DEF#             absoudre  ai3P                       absolurent     0
16                  #DEF#            abstraire  ai3P                     abstrayèrent     0
28                  #DEF#             accroire  ai3P                            #DEF#     0
109                 #DEF#                ardre  ai3P                            #DEF#     0
153                 #DEF#               braire  ai3P                        brayèrent     0
188                 #DEF#              chaloir  ai3P                            #DEF#     0
255                 #DEF#                clore  ai3P                            #DEF#     0
278                 #DEF#            comparoir  ai3P                            #DEF#     0
327                 #DEF#         discontinuer  ai3P                  discontinuèrent     0
377                 #DEF#            dissoudre  ai3P                      dissolurent     0
389                 #DEF#            distraire  ai3P                     distrayèrent     0
401                 #DEF#                douer  ai3P                         douèrent     0
463                 #DEF#              déclore  ai3P                            #DEF#     0
486                 #DEF#              enclore  ai3P                            #DEF#     0
501                 #DEF#              endêver  ai3P                       endêvèrent     0
551                 #DEF#                ester  ai3P                         estèrent     0
601                 #DEF#             extraire  ai3P                      extrayèrent     0
628                 #DEF#              falloir  ai3P                            #DEF#     0
667                 #DEF#             forfaire  ai3P                        forfirent     0
710                 #DEF#                frire  ai3P                            #DEF#     0
740                 #DEF#                gésir  ai3P                            #DEF#     0
777                 #DEF#               occire  ai3P                            #DEF#     0
829                 #DEF#               paître  ai3P                           purent     0
845                 #DEF#               quérir  ai3P                          quirent     0
895                 #DEF#              reclure  ai3P                        reclurent     0
941                 #DEF#             retraire  ai3P                      retrayèrent     0
953                 #DEF#             revaloir  ai3P                       revalurent     0
991                 #DEF#                seoir  ai3P                            #DEF#     0
1031                #DEF#           soustraire  ai3P                    soustrayèrent     0
1043                #DEF#             surfaire  ai3P                        surfirent     0
1089                #DEF#               traire  ai3P                        trayèrent     0
1101                #DEF#                urger  ai3P                         urgèrent     0
1145                #DEF#               échoir  ai3P                         échurent     1
1190                #DEF#               éclore  ai3P                            #DEF#     0
1235                2vrEr              oeuvrer  ai3P                        œuvrèrent     1
1286             9pdEjtEr              updater  ai3P                       updatèrent     0
1337                9rtEr              heurter  ai3P                       heurtèrent     7
1410             ES6lOnEr           échelonner  ai3P                    échelonnèrent     0
1473              ES6vlEr            écheveler  ai3P                     échevelèrent     0
1503                 ESEr               aicher  ai3P                        aichèrent     0
1530               ESOdEr             échauder  ai3P                      échaudèrent     0
1581               ESOfEr            échauffer  ai3P                     échauffèrent     2
1635             ESafOdEr           échafauder  ai3P                    échafaudèrent     0
1687               ESapEr             échapper  ai3P                      échappèrent    29
1738              ESarnEr             écharner  ai3P                      écharnèrent     0
1789              ESarpEr             écharper  ai3P                      écharpèrent     0
1853               ESinEr              échiner  ai3P                       échinèrent     1
1912                ESwEr              échouer  ai3P                       échouèrent    26
1960               ESâZEr             échanger  ai3P                      échangèrent    12
2011              ESâkrEr            échancrer  ai3P                     échancrèrent     0
2049               ESâpir             échampir  ai3P                      échampirent     0
2115              EZEktEr              éjecter  ai3P                       éjectèrent     0
2166             EZakylEr             éjaculer  ai3P                      éjaculèrent     0
2217              EbErZEr             héberger  ai3P                      hébergèrent     2
2247             EbErlHEr             éberluer  ai3P                      éberluèrent     0
2319               EbOSEr             ébaucher  ai3P                      ébauchèrent     0
2370              EbOrJEr             éborgner  ai3P                      éborgnèrent     0
2412                Ebair               ébahir  ai3P                        ébahirent     0
2476              EbarbEr              ébarber  ai3P                       ébarbèrent     0
2517               Ebatir              ébattre  ai3P                       ébattirent     0
2562               Ebluir              éblouir  ai3P                       éblouirent     0
2613               Ebobir              ébaubir  ai3P                       ébaubirent     0
2664               Ebodir              ébaudir  ai3P                       ébaudirent     0
2728              EbrESEr             ébrécher  ai3P                      ébréchèrent     1
2779             EbrHitEr             ébruiter  ai3P                      ébruitèrent     0
2818               EbruEr              ébrouer  ai3P                       ébrouèrent     1
2881              EbrâSEr            ébrancher  ai3P                     ébranchèrent     0
2932              EbrâlEr             ébranler  ai3P                      ébranlèrent     8
2983             EbujâtEr         ébouillanter  ai3P                  ébouillantèrent     0
3034               EbulEr              ébouler  ai3P                       éboulèrent     0
3085             EburifEr           ébouriffer  ai3P                    ébouriffèrent     0
3136               EbuzEr              ébouser  ai3P                       ébousèrent     0
3187                 EdEr                aider  ai3P                         aidèrent    26
3231              EdifjEr              édifier  ai3P                       édifièrent     1
3282              EdiktEr              édicter  ai3P                       édictèrent     0
3333               EditEr               éditer  ai3P                        éditèrent     1
3388               EdykEr              éduquer  ai3P                       éduquèrent     0
3439            EdylkOrEr            édulcorer  ai3P                     édulcorèrent     0
3493               Ef2jEr           effeuiller  ai3P                    effeuillèrent     0
3523             EfEktHEr            effectuer  ai3P                     effectuèrent     0
3595              EfOrsEr             efforcer  ai3P                      efforcèrent     2
3646               EfarEr              effarer  ai3P                       effarèrent     0
3694             EfaruSEr          effaroucher  ai3P                   effarouchèrent     0
3748               EfasEr              effacer  ai3P                       effacèrent     5
3799               EfilEr              effiler  ai3P                       effilèrent     0
3826             EfilOSEr           effilocher  ai3P                    effilochèrent     0
3880              Efl2rEr            effleurer  ai3P                     effleurèrent     0
3911              Efl2rir            effleurir  ai3P                     effleurirent     0
4003              EfrEjEr             effrayer  ai3P                      effrayèrent     8
4066              EfritEr             effriter  ai3P                      effritèrent     0
4117              EfôdrEr            effondrer  ai3P                     effondrèrent    10
4177               EgEjEr             égailler  ai3P                      égaillèrent     0
4228              EgHijEr            aiguiller  ai3P                     aiguillèrent     0
4255            EgHijOnEr         aiguillonner  ai3P                  aiguillonnèrent     0
4330              EgOrZEr              égorger  ai3P                       égorgèrent     2
4381             EgOzijEr            égosiller  ai3P                     égosillèrent     0
4432               EgalEr               égaler  ai3P                        égalèrent     1
4476             EgalizEr             égaliser  ai3P                      égalisèrent     1
4534               EgarEr               égarer  ai3P                        égarèrent     0
4585               EgizEr             aiguiser  ai3P                      aiguisèrent     1
4615              Egr6nEr              égrener  ai3P                       égrenèrent     0
4687              EgrEnEr             égrainer  ai3P                      égrainèrent     0
4738            EgratiJEr           égratigner  ai3P                    égratignèrent     0
4776                Egrir               aigrir  ai3P                        aigrirent     0
4840               EgutEr             égoutter  ai3P                      égouttèrent     0
4891             EgzEkrEr              exécrer  ai3P                       exécrèrent     0
4942            EgzEkytEr             exécuter  ai3P                      exécutèrent     6
4993             EgzErsEr              exercer  ai3P                       exercèrent     1
5044           EgzOrbitEr            exorbiter  ai3P                     exorbitèrent     0
5095           EgzOrsizEr            exorciser  ai3P                     exorcisèrent     0
5146             EgzOrtEr             exhorter  ai3P                      exhortèrent     1
5197              EgzOsEr            exhausser  ai3P                     exhaussèrent     0
5248            EgzaZErEr             exagérer  ai3P                      exagérèrent     0
5299              EgzalEr              exhaler  ai3P                       exhalèrent     0
5347             EgzaltEr              exalter  ai3P                       exaltèrent     0
5401            EgzaminEr             examiner  ai3P                      examinèrent     6
5452           EgzaspErEr            exaspérer  ai3P                     exaspérèrent     0
5503              EgziZEr               exiger  ai3P                        exigèrent    16
5554              EgzibEr              exhiber  ai3P                       exhibèrent     0
5605              EgzilEr               exiler  ai3P                        exilèrent     1
5656             EgzistEr              exister  ai3P                       existèrent     1
5707            EgzonErEr             exonérer  ai3P                      exonérèrent     0
5758             EgzyltEr              exulter  ai3P                       exultèrent     1
5809              EgzymEr              exhumer  ai3P                       exhumèrent     0
5860          EgzâplifjEr          exemplifier  ai3P                   exemplifièrent     0
5911             EgzâptEr             exempter  ai3P                      exemptèrent     1
5946               Ek2rEr             écoeurer  ai3P           écoeurèrent,écœurèrent     0
5976               Ek2tEr             équeuter  ai3P                      équeutèrent     0
6069           EkOgrafjEr         échographier  ai3P                  échographièrent     0
6120           EkOnOmizEr           économiser  ai3P                    économisèrent     0
6171               EkOpEr               écoper  ai3P                        écopèrent     2
6222              EkOrSEr             écorcher  ai3P                      écorchèrent     0
6273              EkOrnEr              écorner  ai3P                       écornèrent     0
6317           EkOrniflEr           écornifler  ai3P                    écorniflèrent     0
6375              EkOrsEr              écorcer  ai3P                       écorcèrent     0
6426               EkOsEr              écosser  ai3P                       écossèrent     0
6477               EkajEr             écailler  ai3P                      écaillèrent     0
6528               EkalEr               écaler  ai3P                        écalèrent     0
6566               Ekarir             équarrir  ai3P                      équarrirent     0
6630            EkarkijEr          écarquiller  ai3P                   écarquillèrent     2
6669            Ekart6lEr            écarteler  ai3P                     écartelèrent     0
6732              EkartEr              écarter  ai3P                       écartèrent     9
6783            EkilibrEr           équilibrer  ai3P                    équilibrèrent     0
6834               EkipEr              équiper  ai3P                       équipèrent     0
6917             Ekivalyr           équivaloir  ai3P                     équivalurent     0
6936             EkivokEr           équivoquer  ai3P                    équivoquèrent     0
6987              EklErEr             éclairer  ai3P                      éclairèrent     1
7022             EklErsir            éclaircir  ai3P                     éclaircirent     0
7089              EklOpEr              écloper  ai3P                       éclopèrent     0
7140            EklabusEr          éclabousser  ai3P                   éclaboussèrent     0
7191              EklatEr              éclater  ai3P                       éclatèrent    14
7242             EklipsEr             éclipser  ai3P                      éclipsèrent     0
7293              EklyzEr              écluser  ai3P                       éclusèrent     0
7344              EkrEmEr              écrémer  ai3P                       écrémèrent     0
7395              EkrEtEr              écrêter  ai3P                       écrêtèrent     0
7446            EkrabujEr         écrabouiller  ai3P                  écrabouillèrent     0
7497              EkrazEr              écraser  ai3P                       écrasèrent    11
7542              EkrijEr               écrier  ai3P                        écrièrent     9
7629            EkrivajEr          écrivailler  ai3P                   écrivaillèrent     0
7661              Ekrivir               écrire  ai3P                       écrivirent    14
7689               EkruEr              écrouer  ai3P                       écrouèrent     0
7737              EkrulEr             écrouler  ai3P                      écroulèrent     9
7790               Ekrwir              écrouir  ai3P                       écrouirent     0
7854              EksEdEr              excéder  ai3P                       excédèrent     0
7905              EksElEr             exceller  ai3P                      excellèrent     0
7956             EksEptEr             excepter  ai3P                      exceptèrent     0
8007           EksOfisjEr          ex-officier  ai3P                   ex-officièrent     0
8058           EksfiltrEr            exfiltrer  ai3P                     exfiltrèrent     0
8109              EksipEr              exciper  ai3P                       excipèrent     0
8160              EksizEr              exciser  ai3P                       excisèrent     0
8211            EksklamEr             exclamer  ai3P                      exclamèrent     1
8262             EkskyzEr              excuser  ai3P                       excusèrent     3
8313            EkspEdjEr             expédier  ai3P                      expédièrent     2
8364          EkspEktOrEr           expectorer  ai3P                    expectorèrent     0
8415         EkspErimâtEr         expérimenter  ai3P                  expérimentèrent     1
8466          EkspErtizEr           expertiser  ai3P                    expertisèrent     0
8517            EkspOrtEr             exporter  ai3P                      exportèrent     0
8568             EkspOzEr              exposer  ai3P                       exposèrent     5
8607          EkspatrijEr            expatrier  ai3P                     expatrièrent     0
8684             EkspirEr              expirer  ai3P                       expirèrent     0
8721              EkspjEr               expier  ai3P                        expièrent     0
8772            EksplOrEr             explorer  ai3P                      explorèrent     4
8823            EksplOzEr             exploser  ai3P                      explosèrent    10
8874            EksplikEr            expliquer  ai3P                     expliquèrent    10
8925          EksplisitEr           expliciter  ai3P                    explicitèrent     0
8976           EksplwatEr            exploiter  ai3P                     exploitèrent     3
9015         EksprOprijEr           exproprier  ai3P                    exproprièrent     0
9078            EksprimEr             exprimer  ai3P                      exprimèrent     4
9129            EkspylsEr             expulser  ai3P                      expulsèrent     3
9180            EkspyrZEr             expurger  ai3P                      expurgèrent     0
9210            EkstEnHEr             exténuer  ai3P                      exténuèrent     0
9282        EkstErjOrizEr         extérioriser  ai3P                  extériorisèrent     0
9333          EkstErminEr           exterminer  ai3P                    exterminèrent     2
9384            EkstOrkEr            extorquer  ai3P                     extorquèrent     0
9435            EkstazjEr             extasier  ai3P                      extasièrent     0
9486            EkstirpEr             extirper  ai3P                      extirpèrent     2
9576            EkstradEr             extrader  ai3P                      extradèrent     0
9627          EkstrapOlEr           extrapoler  ai3P                    extrapolèrent     0
9678          EkstravagEr          extravaguer  ai3P                   extravaguèrent     0
9729              EksydEr              exsuder  ai3P                       exsudèrent     0
9780             EksâtrEr            excentrer  ai3P                     excentrèrent     0
9831               EkulEr              écouler  ai3P                       écoulèrent    32
9882              EkurtEr             écourter  ai3P                      écourtèrent     0
9933               EkutEr              écouter  ai3P                       écoutèrent    16
9984               EkylEr               éculer  ai3P                        éculèrent     0
10035              EkymEr               écumer  ai3P                        écumèrent     2
10097           EkôdHizir            éconduire  ai3P                    éconduisirent     1
10145              ElEZir               élégir  ai3P                        élégirent     0
10209        ElEktrOkytEr         électrocuter  ai3P                  électrocutèrent     0
10260         ElEktrifjEr          électrifier  ai3P                   électrifièrent     2
10311          ElEktrizEr           électriser  ai3P                    électrisèrent     1
10362            ElEnizEr           helléniser  ai3P                    hellénisèrent     0
10413            ElabOrEr             élaborer  ai3P                      élaborèrent     4
10464              ElagEr              élaguer  ai3P                       élaguèrent     0
10502             ElarZir              élargir  ai3P                       élargirent     1
10570              ElimEr               élimer  ai3P                        élimèrent     0