In [29]:
import pandas as pd
from scipy import stats

In [8]:
nomLexiqueOrg="/Volumes/BroadExt/Dropbox/Travail/Recherche/BoBoHe/datasets/vlexique/Lexique3.txt"

In [ ]:
dfL=pd.read_csv(nomLexiqueOrg,sep="\t")

In [28]:
df=dfL[['3_lemme', '4_cgram', '5_genre', '6_nombre', '9_freqfilms2', '10_freqlivres','11_infover']]
df.columns=["lemme","cat","genre","nombre","freqF","freqL","ver"]
dfV=df.loc[df.cat.isin(["AUX","VER"])]
dfV.head()

       lemme  cat genre nombre    freqF    freqL          ver
1      avoir  AUX   NaN    NaN  6350.91  2926.69  ind:pre:3s;
2      avoir  VER   NaN    NaN  5498.34  1669.39  ind:pre:3s;
18  abaisser  VER   NaN    NaN     0.00     2.64  ind:pas:3s;
19  abaisser  VER   NaN    NaN     0.10     0.07  ind:pas:1s;
20  abaisser  VER   NaN    NaN     0.00     0.41  ind:imp:3p;

In [53]:
dfV['freqF'] = dfV['freqF'].fillna(0)
dfV['relF'] = dfV['freqF'] / dfV['freqF'].sum()
print("total Films",dfV['freqF'].sum())
dfV['freqL'] = dfV['freqL'].fillna(0)
dfV['relL'] = dfV['freqL'] / dfV['freqL'].sum()
print("total Livres",dfV['freqL'].sum())
statistic,p_value=stats.ks_2samp(dfV['relF'], dfV['relL'])
print(f"Statistique KS : {statistic:.2%}")
print(f"p-value : {p_value:.8f}\n")

total Films 225024.19
total Livres 169653.21
Statistique KS : 42.32%
p-value : 0.00000000

/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/1562779528.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfV['freqF'] = dfV['freqF'].fillna(0)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/1562779528.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfV['relF'] = dfV['freqF'] / dfV['freqF'].sum()
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/1562779528.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfV['freqL'] = dfV['freqL'].fillna(0)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/1562779528.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfV['relL'] = dfV['freqL'] / dfV['freqL'].sum()

In [51]:
seuil=10
cond=(dfV.freqF>seuil)&(dfV.freqL>seuil)
statistic,p_value=stats.ks_2samp(dfV.loc[cond]['relF'], dfV.loc[cond]['relL'])
print(f"Statistique KS : {statistic:.2%}")
print(f"p-value : {p_value:.8f}\n")  
dfV.loc[cond]

Statistique KS : 12.77%
p-value : 0.00000000

,lemme,cat,genre,nombre,freqF,freqL,ver,relF,relL
1,avoir,AUX,NaN,NaN,6350.91,2926.69,ind:pre:3s;,0.028223,0.017251
2,avoir,VER,NaN,NaN,5498.34,1669.39,ind:pre:3s;,0.024434,0.009840
58,abandonner,VER,NaN,NaN,24.04,15.54,imp:pre:2s;ind:pre:1s;ind:pre:3s;sub:pre:3s;,0.000107,0.000092
60,abandonner,VER,NaN,NaN,28.37,27.70,ind:pre:2p;inf;,0.000126,0.000163
82,abandonner,VER,m,s,22.56,23.92,par:pas;,0.000100,0.000141
...,...,...,...,...,...,...,...,...,...
142546,Èviter,VER,NaN,NaN,53.71,60.07,inf;;,0.000239,0.000354
142650,Ítre,AUX,NaN,NaN,260.22,51.89,ind:pre:2p;,0.001156,0.000306
142651,Ítre,VER,NaN,NaN,1002.88,195.54,imp:pre:2p;ind:pre:2p;,0.004457,0.001153
142652,Ítre,AUX,NaN,NaN,725.09,685.47,inf;,0.003222,0.004040
142654,Ítre,VER,NaN,NaN,1111.69,505.61,inf;;inf;;inf;;,0.004940,0.002980

In [55]:
df['freqF'] = df['freqF'].fillna(0)
df['relF'] = df['freqF'] / df['freqF'].sum()
print("total Films",df['freqF'].sum())
df['freqL'] = df['freqL'].fillna(0)
df['relL'] = df['freqL'] / df['freqL'].sum()
print("total Livres",df['freqL'].sum())
statistic,p_value=stats.ks_2samp(df['relF'], df['relL'])
print(f"Statistique KS : {statistic:.2%}")
print(f"p-value : {p_value:.8f}\n")

total Films 907213.0900000001
total Livres 913709.88
Statistique KS : 35.99%
p-value : 0.00000000

/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/868998127.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['freqF'] = df['freqF'].fillna(0)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/868998127.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['relF'] = df['freqF'] / df['freqF'].sum()
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/868998127.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['freqL'] = df['freqL'].fillna(0)
/var/folders/dy/h2nycthd7qjbd6qkb5h8t0nm0000gn/T/ipykernel_55439/868998127.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['relL'] = df['freqL'] / df['freqL'].sum()

In [65]:

for seuil in range (0,4000,50):
    cond=(df.freqF>seuil)&(df.freqL>seuil)
    statistic,p_value=stats.ks_2samp(df.loc[cond]['relF'], df.loc[cond]['relL'])
    print(f"Statistique KS : {statistic:.2%}")
    print(f"p-value : {p_value:.8f}\n")  
    print(seuil,len(df.loc[cond]))

Statistique KS : 28.58%
p-value : 0.00000000

0 87405
Statistique KS : 5.31%
p-value : 0.11337553

50 1016
Statistique KS : 8.63%
p-value : 0.03167695

100 556
Statistique KS : 11.14%
p-value : 0.01656062

150 386
Statistique KS : 12.30%
p-value : 0.01860672

200 309
Statistique KS : 14.01%
p-value : 0.01282471

250 257
Statistique KS : 14.35%
p-value : 0.02326189

300 216
Statistique KS : 16.13%
p-value : 0.01570764

350 186
Statistique KS : 16.67%
p-value : 0.02206272

400 162
Statistique KS : 17.57%
p-value : 0.02059778

450 148
Statistique KS : 17.16%
p-value : 0.03841444

500 134
Statistique KS : 15.62%
p-value : 0.08782223

550 128
Statistique KS : 14.17%
p-value : 0.18016860

600 120
Statistique KS : 12.28%
p-value : 0.35756119

650 114
Statistique KS : 8.82%
p-value : 0.82465541

700 102
Statistique KS : 9.18%
p-value : 0.80572570

750 98
Statistique KS : 8.60%
p-value : 0.88409748

800 93
Statistique KS : 9.09%
p-value : 0.86310534

850 88
Statistique KS : 9.30%
p-value : 0.85374424

900 86
Statistique KS : 9.76%
p-value : 0.83319466

950 82
Statistique KS : 9.76%
p-value : 0.83319466

1000 82
Statistique KS : 10.39%
p-value : 0.80373088

1050 77
Statistique KS : 10.96%
p-value : 0.77678922

1100 73
Statistique KS : 10.00%
p-value : 0.87866613

1150 70
Statistique KS : 10.14%
p-value : 0.87325705

1200 69
Statistique KS : 10.45%
p-value : 0.86174841

1250 67
Statistique KS : 12.12%
p-value : 0.72147164

1300 66
Statistique KS : 12.12%
p-value : 0.72147164

1350 66
Statistique KS : 12.31%
p-value : 0.71264490

1400 65
Statistique KS : 12.31%
p-value : 0.71264490

1450 65
Statistique KS : 12.70%
p-value : 0.69425225

1500 63
Statistique KS : 13.11%
p-value : 0.67484503

1550 61
Statistique KS : 13.56%
p-value : 0.65439032

1600 59
Statistique KS : 12.07%
p-value : 0.79677957

1650 58
Statistique KS : 10.71%
p-value : 0.90875265

1700 56
Statistique KS : 12.73%
p-value : 0.76951071

1750 55
Statistique KS : 14.81%
p-value : 0.59848426

1800 54
Statistique KS : 14.81%
p-value : 0.59848426

1850 54
Statistique KS : 13.21%
p-value : 0.74953067

1900 53
Statistique KS : 13.46%
p-value : 0.73896846

1950 52
Statistique KS : 13.46%
p-value : 0.73896846

2000 52
Statistique KS : 13.46%
p-value : 0.73896846

2050 52
Statistique KS : 13.46%
p-value : 0.73896846

2100 52
Statistique KS : 12.00%
p-value : 0.86926189

2150 50
Statistique KS : 12.00%
p-value : 0.86926189

2200 50
Statistique KS : 12.00%
p-value : 0.86926189

2250 50
Statistique KS : 12.00%
p-value : 0.86926189

2300 50
Statistique KS : 14.89%
p-value : 0.68001748

2350 47
Statistique KS : 17.39%
p-value : 0.49431914

2400 46
Statistique KS : 18.60%
p-value : 0.45062271

2450 43
Statistique KS : 14.63%
p-value : 0.77891491

2500 41
Statistique KS : 13.16%
p-value : 0.90325333

2550 38
Statistique KS : 10.81%
p-value : 0.98455995

2600 37
Statistique KS : 10.81%
p-value : 0.98455995

2650 37
Statistique KS : 10.81%
p-value : 0.98455995

2700 37
Statistique KS : 10.81%
p-value : 0.98455995

2750 37
Statistique KS : 10.81%
p-value : 0.98455995

2800 37
Statistique KS : 11.43%
p-value : 0.97938401

2850 35
Statistique KS : 11.43%
p-value : 0.97938401

2900 35
Statistique KS : 8.82%
p-value : 0.99960925

2950 34
Statistique KS : 9.38%
p-value : 0.99932591

3000 32
Statistique KS : 9.38%
p-value : 0.99932591

3050 32
Statistique KS : 9.68%
p-value : 0.99911526

3100 31
Statistique KS : 9.68%
p-value : 0.99911526

3150 31
Statistique KS : 9.68%
p-value : 0.99911526

3200 31
Statistique KS : 9.68%
p-value : 0.99911526

3250 31
Statistique KS : 9.68%
p-value : 0.99911526

3300 31
Statistique KS : 9.68%
p-value : 0.99911526

3350 31
Statistique KS : 9.68%
p-value : 0.99911526

3400 31
Statistique KS : 9.68%
p-value : 0.99911526

3450 31
Statistique KS : 9.68%
p-value : 0.99911526

3500 31
Statistique KS : 13.33%
p-value : 0.95784629

3550 30
Statistique KS : 13.33%
p-value : 0.95784629

3600 30
Statistique KS : 13.33%
p-value : 0.95784629

3650 30
Statistique KS : 13.33%
p-value : 0.95784629

3700 30
Statistique KS : 14.29%
p-value : 0.94408581

3750 28
Statistique KS : 14.29%
p-value : 0.94408581

3800 28
Statistique KS : 14.29%
p-value : 0.94408581

3850 28
Statistique KS : 14.81%
p-value : 0.93566223

3900 27
Statistique KS : 14.81%
p-value : 0.93566223

3950 27